<?php
    require_once('Connection.php');

    class Alert {
        private $id;
        private $longitude;
        private $latitude;
        private $type;
        private $description;
        private $isSolved;

        public function __construct ($longitude, $latitude, $type, $description, $isSolved)
        {
            $this->longitude = $longitude;
            $this->latitude = $latitude;
            $this->type = $type;
            $this->desciption = $description;
            $this->isSolved = $isSolved;
        }

        // method used to send the object to the database (id is autogenerated)
        public function create(): bool
        {
            $connection = Connection::Instance();
            $sql = "INSERT INTO alert (longitude, latitude, type, description, isSolved) VALUES ("
                    .$this->longitude.", ".$this->latitude.", '".$this->type."', '".$this->description."', ".$this->isSolved.");";
            if (!($ok = $connection->exec($sql)))
                return false;
            $sql = "SELECT TOP(1) id FROM alert ORDER BY id DESC";
            try
            {
                foreach ($connection->query($sql) as $row)
                    $this->id = $row['id'];
                return true;
            }
            catch (PDOException $e) {
                return false;
            }
        }

        //method used to load the information related to the object with this specific id
        public function load(): bool
        {
            $connection = Connection::Instance();
            $sql = "SELECT * FROM alert WHERE id = ".$this->id.";";
            try
            {
                foreach ($connection->query($sql) as $row)
                {
                    $this->longitude = $row['longitude'];
                    $this->latitude = $row['latitude'];
                    $this->type = $row['type'];
                    $this->desciption = $row['description'];
                    $this->isSolved = $row['isSolved'];
                }
                return true;
            }
            catch (PDOException $e) {
                return false;
            }

        }

        //method used to remove the object with this specific id
        public function remove(): bool
        {
            $connection = Connection::Instance();
            $sql = "DELETE FROM alert WHERE id = ".$this->id.";";
            if (!($ok = $connection->exec($sql)))
                return false;
            return true;
        }

        public function getId(): int
        {
            return $this->id;
        }

        public function setId($id): void
        {
            $this->id = $id;
        }

        public function getLongitutde(): float
        {
            return $this->longitude;
        }

        public function getLatitude()
        {
            return $this->latitude;
        }

        public function getType()
        {
            return $this->type;
        }

        public function getDescription()
        {
            return $this->desciption;
        }

        public function getIsSolved()
        {
            return $this->isSolved;
        }
    }
?>