<?php
    require_once('Connection.php');

    class CrisisUser {
        private $id;
        private $firstname;
        private $lastname;
        private $email;
        private $password;
        private $country;
        private $city;
        private $zipcode;
        private $phone;

        public function __construct ($firstname, $lastname, $email, $password, $country, $city, $zipcode, $phone)
        {
            $this->firstname = $firstname;
            $this->lastname = $lastname;
            $this->email = $email;
            $this->password = $password;
            $this->country = $country;
            $this->city = $city;
            $this->zipcode = $zipcode;
            $this->phone = $phone;
        }

        // method used to send the object to the database (id is autogenerated)
        public function create(): bool
        {
            $connection = Connection::Instance();
            $sql = "INSERT INTO crisis_user (firstname, lastname, email, password, country, city, zipcode, phone) VALUES ('"
                .$this->firstname."', '".$this->lastname."', '".$this->email."', '".$this->password."', '".$this->country."', '".$this->city."', '".$this->zipcode."', '".$this->phone."');";
            if (!($ok = $connection->exec($sql)))
                return false;
            $sql = "SELECT TOP(1) id FROM crisis_user ORDER BY id DESC";
            try
            {
                foreach ($connection->query($sql) as $row)
                    $this->id = $row['id'];
                return true;
            }
            catch (PDOException $e) {
                return false;
            }
        }

        //method used to load the information related to the object with this specific id
        public function load(): bool
        {
            $connection = Connection::Instance();
            $sql = "SELECT * FROM crisis_user WHERE id = ".$this->id.";";
            try
            {
                foreach ($connection->query($sql) as $row)
                {
                    $this->firstname = $row['firstname'];
                    $this->lastname = $row['lastname'];
                    $this->email = $row['email'];
                    $this->password = $row['password'];
                    $this->country = $row['country'];
                    $this->city = $row['city'];
                    $this->zipcode = $row['zipcode'];
                    $this->phone = $row['phone'];
                }
                return true;
            }
            catch (PDOException $e) {
                return false;
            }
        }

        //method used to remove the object with this specific id
        public function remove(): bool
        {
            $connection = Connection::Instance();
            $sql = "DELETE FROM crisis_user WHERE id = ".$this->id.";";
            if (!($ok = $connection->exec($sql)))
                return false;
            return true;
        }

        public function getId(): int
        {
            return $this->id;
        }

        public function setId($id): void
        {
            $this->id = $id;
        }
    }
?>