<?php
    require_once('Connection.php');

    class MissingPerson {
        private $id;
        private $firstname;
        private $lastname;
        private $lastInteraction;
        private $description;
        private $photo;
        private $id_alert;
        private $id_user;

        public function __construct ($firstname, $lastname, $lastInteraction, $description, $photo, $id_alert, $id_user)
        {
            $this->firstname = $firstname;
            $this->lastname = $lastname;
            $this->lastInteraction = $lastInteraction;
            $this->description = $description;
            $this->photo = $photo;
            $this->id_alert = $id_alert;
            $this->id_user = $id_user;
        }

        // method used to send the object to the database (id is autogenerated)
        public function create(): bool
        {
            $connection = Connection::Instance();
            $sql = "INSERT INTO missing_person (firstname, lastname, lastInteraction, description, photo, id_alert, id_user) VALUES ('"
                .$this->firstname."', '".$this->lastname."', '".$this->lastInteraction."', '".$this->description."', ".$this->photo.", ".$this->id_alert.", ".$this->id_user.");";
            if (!($ok = $connection->exec($sql)))
                return false;
            $sql = "SELECT TOP(1) id FROM missing_person ORDER BY id DESC";
            try
            {
                foreach ($connection->query($sql) as $row)
                    $this->id = $row['id'];
                return true;
            }
            catch (PDOException $e) {
                return false;
            }
        }

        //method used to load the information related to the object with this specific id
        public function load(): bool
        {
            $connection = Connection::Instance();
            $sql = "SELECT * FROM missing_person WHERE id = ".$this->id.";";
            try
            {
                foreach ($connection->query($sql) as $row)
                {
                    $this->firstname = $row['firstname'];
                    $this->lastname = $row['lastname'];
                    $this->lastInteraction = $row['lastInteraction'];
                    $this->description = $row['description'];
                    $this->photo = $row['photo'];
                    $this->id_alert = $row['id_alert'];
                    $this->id_user = $row['id_user'];
                }
                return true;
            }
            catch (PDOException $e) {
                return false;
            }

        }

        //method used to remove the object with this specific id
        public function remove(): bool
        {
            $connection = Connection::Instance();
            $sql = "DELETE FROM missing_person WHERE id = ".$this->id.";";
            if (!($ok = $connection->exec($sql)))
                return false;
            return true;
        }

        public function getId(): int
        {
            return $this->id;
        }

        public function setId($id): void
        {
            $this->id = $id;
        }
    }
?>