<?php
    require_once('Connection.php');

    class UserAlert {
        private $id;
        private $id_user;
        private $id_alert;

        public function __construct ($id_user, $id_alert)
        {
            $this->id_user = $id_user;
            $this->id_alert = $id_alert;
        }

        // method used to send the object to the database (id is autogenerated)
        public function create(): bool
        {
            $connection = Connection::Instance();
            $sql = "INSERT INTO user_alert (id_user, id_alert) VALUES ("
                .$this->id_user.", ".$this->id_alert.");";
            if (!($ok = $connection->exec($sql)))
                return false;
            $sql = "SELECT TOP(1) id FROM user_alert ORDER BY id DESC";
            try
            {
                foreach ($connection->query($sql) as $row)
                    $this->id = $row['id'];
                return true;
            }
            catch (PDOException $e) {
                return false;
            }
        }

        //method used to load the information related to the object with this specific id
        public function load(): bool
        {
            $connection = Connection::Instance();
            $sql = "SELECT * FROM user_alert WHERE id = ".$this->id.";";
            try
            {
                foreach ($connection->query($sql) as $row)
                {
                    $this->id_user = $row['id_user'];
                    $this->id_alert = $row['id_alert'];
                }
                return true;
            }
            catch (PDOException $e) {
                return false;
            }
        }

        //method used to save the current object with this specific id into the database
        public function save(): bool
        {
            $connection = Connection::Instance();
            $sql = "UPDATE user_alert SET "
                ."id_user = '" . $this->id_user."', "
                ."id_alert = " . $this->id_alert . " "
                ."WHERE id = " . $this->id . ";";
            if (!($ok = $connection->exec($sql)))
                return false;
            return true;
        }

        //method used to remove the object with this specific id
        public function remove(): bool
        {
            $connection = Connection::Instance();
            $sql = "DELETE FROM user_alert WHERE id = ".$this->id.";";
            if (!($ok = $connection->exec($sql)))
                return false;
            return true;
        }

        public function getId(): int
        {
            return $this->id;
        }

        public function setId($id): void
        {
            $this->id = $id;
        }

        public function getIdUser()
        {
            return $this->id_user;
        }

        public function setIdUser($id_user)
        {
            $this->id_user = $id_user;
        }

        public function getIdAlert()
        {
            return $this->id_alert;
        }

        public function setIdAlert($id_alert)
        {
            $this->id_alert = $id_alert;
        }
    }
?>